server:
  port: 9999

spring:
  redis:
    lettuce:
      pool:
        MaxTotal: 50
        minIdle: 1
        maxWaitMillis: 5000
        maxIdle: 5
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
    mac-resource:
      database: 19
      hostName: r-uxxxxxxxxapd.redis.rds.aliyuncs.com
      port: 6379
      timeout: 5000
      password: kxxxxxxx@KyL
